#!/usr/bin/env python

import sys
import docker

from .containers import DockerContainer

# class DockerGroups(object):
#
#    def __init__(self, config):
#        self.

dockers = [
    DockerContainer('apt-cacher-ng'),
    DockerContainer('gitolite'),
    DockerContainer('cgit'),
    DockerContainer('pypicloud'),
    ]


def start_dockers():
    for d in dockers:
        d.start()


def stop_dockers():
    for d in dockers:
        d.stop()


if __name__ == "__main__":

    if len(sys.argv) != 2:
        sys.exit(2)

    dc = docker.Client('/var/run/docker.sock')

    if sys.argv[1] == 'start':
        start_dockers()
    elif sys.argv[1] == 'stop':
        stop_dockers()
    else:
        sys.stderr.write("Invalid arguments\n")
        sys.exit(2)

# vim:set ft=python sw=4 et spell spelllang=en:
